# Generated by Django 3.1.7 on 2021-03-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
