# Generated by Django 3.1.7 on 2021-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullo', '0005_auto_20210321_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='d',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
