# Generated by Django 3.1.7 on 2021-03-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pullo', '0006_shoes_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='d',
        ),
    ]
