# Generated by Django 3.1.7 on 2021-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pullo', '0007_remove_shoes_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='promotion',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
